# Generated by Django 6.0.2 on 2026-02-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_id_alter_telegramuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание книги'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='review',
            field=models.TextField(blank=True, verbose_name='Мои впечатления'),
        ),
    ]
