# Generated by Django 6.0.2 on 2026-02-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_userbook_description_userbook_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
