# Generated by Django 6.0.2 on 2026-02-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_cover_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='В избранном'),
        ),
    ]
