# Generated by Django 6.0.2 on 2026-03-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_userbook_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания чтения'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала чтения'),
        ),
    ]
